name: GchantBase
main: me.greggkr.gchantbase.GchantBase
version: 1.2.1
description: Base plugin for Gchant.
author: SirGregg

commands:
  gchant:
    description: Main command for GchantBase
    aliases: [customenchant, ce, gc, gchantbase]

permissions:
  gchant.command.help:
    description: Allows you to use /gc help
    default: true
  gchant.command.enchant:
    description: Allows you to use /gc enchant
    default: op
  gchant.command.list:
    description: Allows you to use /gc list
    default: true